@startuml
!include https://raw.githubusercontent.com/anorm/plantuml-ext/main/util.puml
hide circle
hide empty member

!$WRAPCOL_TITLE=14
!$WRAPCOL_DESC=30
!$WRAPCOL_EXAMPLE=30

skinparam class<<Entity>> {
    BackgroundColor white
    HeaderBackgroundColor AntiqueWhite
    AttributeFontSize 12
    FontSize 14
}
hide <<Entity>> stereotype
skinparam class<<Entity_Ext>> {
    BackgroundColor white
    HeaderBackgroundColor #eee
    AttributeFontColor #777
    AttributeFontSize 12
    FontSize 14
}
hide <<Entity_Ext>> stereotype

!function $getLink($link)
  !if ($link!="")
    !return "[[" + $link + "]]"
  !else
    !return ""
  !endif
!endfunction

!function $getStereo($stereo)
  !if ($stereo!="")
    !return "<<" + $stereo + ">>"
  !else
    !return ""
  !endif
!endfunction

!function $getName($name, $description, $example)
    !$ret = "\n= " + $replace($wrap($name, $WRAPCOL_TITLE), "\n", "\n= ") + "\n"
    !if ($description != "")
        !$ret = $ret + "\n " + $wrap($description, $WRAPCOL_DESC) + " "
        !$ret = $ret + "\n"
    !endif
    !if ($example != "")
        !$ret = $ret + "\n//" + $replace($wrap("Ex: "+$example, $WRAPCOL_EXAMPLE), "\n", "//\n//") + "//"
    !endif
    !return $ret
!endfunction

!function $getRelationText($description, $params)
    !$ret = "**"+$description+"**"
    !if ($params != "")
        !$ret = $ret + "\n" + $replace($params, "|", "\n")
    !endif
    !return $ret
!endfunction

!unquoted procedure Entity($id, $name, $description="", $example="")
class "$getName($name, $description, $example)" as $id <<Entity>>
!endprocedure

!unquoted procedure Entity_Ext($id, $name, $description="", $example="")
class "$getName($name, $description, $example)" as $id <<Entity_Ext>>
!endprocedure

!unquoted procedure Property($name, $description="", $example="")
<#transparent,#transparent>|= $name | $wrap($description, $WRAPCOL_DESC) | $wrap($example, $WRAPCOL_EXAMPLE) |
!endprocedure

!unquoted procedure Rel_($from, $description, $to, $params="", $arrow="-->")
$from $arrow $to: $getRelationText($description, $params)
!endprocedure

!unquoted procedure Rel($from, $description, $to, $params="")
Rel_($from, $description, $to, $params, "-->")
!endprocedure

!unquoted procedure Rel_U($from, $description, $to, $params="")
Rel_($from, $description, $to, $params, "-U->")
!endprocedure

!unquoted procedure Rel_D($from, $description, $to, $params="")
Rel_($from, $description, $to, $params, "-D->")
!endprocedure

!unquoted procedure Rel_L($from, $description, $to, $params="")
Rel_($from, $description, $to, $params, "-L->")
!endprocedure

!unquoted procedure Rel_R($from, $description, $to, $params="")
Rel_($from, $description, $to, $params, "-R->")
!endprocedure

@enduml
